controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app.logout:
    path: /logout
    methods: ['POST', 'GET']

twilio_auth:
    path: /auth/user/{user}
    controller: App\Controller\TwilioController::twilioAuth
    methods: [GET]

